config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [] do
     resources :posts
  end

  get "users/:user_id/posts/:id/star", to: "posts#star", as: :star

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    #here the format is validating only WHEN an image_url is passed, but if not then it is not validated
    validates_format_of :image_url, :with => %r{(^$)|(^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?(gif|jpg|png|jpeg|bmp)$)}ix, :message => 'must be a URL for GIF, JPG, PNG, JPEG, or BMP image'
    #HW: add a validator to make an image_url required
    validates_presence_of :image_url
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        if user_signed_in?
            @posts = Post.all.reverse
        else 
            redirect_to new_user_session_path
        end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_user
  before_action :set_post, only: [:show, :edit, :update, :destroy, :star]
  before_action :authenticate_user!
  before_action :verify_ownership!, except: [:index, :show, :star]

  # GET /posts
  # GET /posts.json
  def index
    @posts = @user.posts.reverse
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = @user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = @user.posts.build(post_params)

    if @post.save
        redirect_to user_posts_path(@user), notice: 'Post was successfully created.'
    else
        render :new
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    if @post.update(post_params)
        redirect_to user_posts_path(@user), notice: 'Post was successfully updated.'
    else
        render :edit
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    redirect_to user_posts_url(@user), notice: 'Post was successfully destroyed.'
  end

  # POST users/1/posts/1/star
  # PENDING CONTROLLER ACTION

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:user_id])
    end
    
    def set_post
      @post = @user.posts.find(params[:id])
    end

    def verify_ownership!
      if current_user.id != @user.id
        redirect_to root_path, alert: "You are not authorized to complete this action."
      end
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:caption, :image_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/application/_post.html.erb
<div class="row">
  <div class="col-sm-8">
    <div class="card">
      <div class="card-header">
         <ul class="nav nav-pills card-header-pills">
           <li class="nav-item mr-auto">
             <%= link_to post.user.email, user_posts_path(post.user), class: "nav-link", id: "post-email-#{post.id}"%>
           </li>
           <% if current_user == post.user %>
                <li class="nav-item">
                    <%= link_to 'Edit', edit_user_post_path(post.user, post), class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to 'Destroy', user_post_path(post.user, post), method: :delete, class: "nav-link" %>
                </li>   
            <% end %>
            <!-- PENDING create a link to star the post --!>
        </ul>
      </div>
      <div class="card-body">
        <img src="<%= post.image_url %>" class="card-img-top order-<%= defined?(post_counter) ? post_counter : "" %> post-<%= post.id %>" alt="...">
      </div>
      <div class="card-footer">
        <p class="card-text"><strong><%= post.user.email %></strong> <%= post.caption %></p>
        <p class="card-text small"><%= post.created_at %></p>

      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<%# This is almost like a for loop for sub-templates.
Rails will the subtemplate in `application/_post.html.erb` for each entry in the @posts collection %>
<%= render partial: "post", collection: @posts %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Oleo+Script&display=swap" rel="stylesheet">
    <%= javascript_pack_tag 'application' %>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-light fixed-top">
      <a class="navbar-brand logo" href="#">Instagram</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item <%= @home ? 'active' : '' %>">
            <a class="nav-link" href="/">Home</a>
          </li>
          <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to "New Post", new_user_post_path(current_user), class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Me", user_posts_path(current_user), class: "nav-link" %>
              </li>    
          <% end %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Account</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <% if user_signed_in? %>
                  <%= link_to "Sign Out", destroy_user_session_path, method: "delete", class: "dropdown-item" %>
              <% else %>
                  <%= link_to "Sign In", new_user_session_path, class: "dropdown-item" %>
              <% end %>
            </div>
          </li>
        </ul>
        
      </div>
    </nav>

    <main role="main" class="container">
        <% unless notice.nil? %>
          <div class="alert alert-success">
            <%= notice %>
          </div>
        <% end %>
        <% unless alert.nil? %>
          <div class="alert alert-danger">
            <%= alert %>
          </div>
        <% end %>
        <%= yield %>

    </main><!-- /.container -->
      
   
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: [@user, post], local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :caption %>
    <%= form.text_area :caption %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_area :image_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', user_post_path(@user, @post) %> |
<%= link_to 'Back', user_posts_path %>

app/views/posts/index.html.erb
<h1 id="user_email"><%= @user.email %></h1>

<br>
<%# This is almost like a for loop for sub-templates.
Rails will use the subtemplate in `application/_post.html.erb` for each entry in the @posts collection %>
<%= render partial: "post", collection: @posts %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', user_posts_path(@user) %>

app/views/posts/show.html.erb
<%# Rails will use the subtemplate in `application/_post.html.erb` %>
<%= render "post", post: @post %>